/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AssessmentCompleteLazyImport = createFileRoute('/assessment-complete')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AssessmentCompleteLazyRoute = AssessmentCompleteLazyImport.update({
  id: '/assessment-complete',
  path: '/assessment-complete',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/assessment-complete.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/assessment-complete': {
      id: '/assessment-complete'
      path: '/assessment-complete'
      fullPath: '/assessment-complete'
      preLoaderRoute: typeof AssessmentCompleteLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/assessment-complete': typeof AssessmentCompleteLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/assessment-complete': typeof AssessmentCompleteLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/assessment-complete': typeof AssessmentCompleteLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assessment-complete'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assessment-complete'
  id: '__root__' | '/' | '/assessment-complete'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AssessmentCompleteLazyRoute: typeof AssessmentCompleteLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AssessmentCompleteLazyRoute: AssessmentCompleteLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/assessment-complete"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/assessment-complete": {
      "filePath": "assessment-complete.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
